# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('queryserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('boxinfo', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='boxes',
        ),
    ]
