# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryserver', '0002_auto_20160124_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socid', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='box',
            name='boxinfo',
        ),
        migrations.AddField(
            model_name='box',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='videoid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='xlen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='ylen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
