# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queryserver', '0003_auto_20160204_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='objectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryserver.Object'),
        ),
        migrations.AlterField(
            model_name='box',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='videoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryserver.Video'),
        ),
        migrations.AlterField(
            model_name='box',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='xlen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='ylen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='object',
            name='sessionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryserver.Session'),
        ),
        migrations.AlterField(
            model_name='query',
            name='sessionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryserver.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='socid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryserver.Soc'),
        ),
        migrations.AlterField(
            model_name='soc',
            name='url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='video',
            name='socid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryserver.Soc'),
        ),
    ]
